name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev, staging ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov bandit safety
    
    - name: Run Unit Tests
      run: |
        pytest tests/ --cov=. --cov-report=xml
    
    - name: SAST Security Scan with Bandit
      run: |
        bandit -r . -f json -o bandit-report.json || true
        bandit -r . -f txt
    
    - name: Dependency Security Check
      run: |
        safety check --json --output safety-report.json || true
        safety check
    
    - name: Build Docker Image
      run: |
        docker build -t todolist-app:${{ github.sha }} .
    
    - name: Run Container for DAST
      run: |
        docker run -d -p 5000:5000 --name test-app todolist-app:${{ github.sha }}
        sleep 10
    
    - name: DAST Security Scan with OWASP ZAP
      uses: zaproxy/action-baseline-scan@v0.10.0
      with:
        target: 'http://localhost:5000'
        rules_file_name: '.zap/rules.tsv'
        cmd_options: '-a'
    
    - name: Stop Test Container
      if: always()
      run: |
        docker stop test-app || true
        docker rm test-app || true
    
    - name: Upload Security Reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json
          report_html.html

  deploy-staging:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Staging
      run: |
        echo "Deploying to staging environment..."
        # Deploy commands akan ditambahkan nanti
