name: CI/CD Pipeline

on:
  push:
    branches: [ main, feature/ci-cd-pipeline ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python3 -m unittest discover tests

    - name: Run Bandit Security Scan
      run: |
        pip install bandit
        bandit -r app

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to staging (dummy)
      run: echo "Deploying to staging server..."
